### ISSUE TITLE
Feature request: Format Document

### ISSUE THREAD

**Issue by karocksjoelee** [on2-dev/nasc-vscode-mac-touchbar#21]

**Comment by nodinosaur** [comment]
I've added a pull request #29 for this as I would find it useful too :)

**Comment by felipenmoura** [comment]
Very promising :)
I just added a comment in the PR

**Comment by nodinosaur** [comment]
Any update on merging this?

**Comment by nodinosaur** [comment]
This is now merged into master 
https://github.com/NascHQ/nasc-vscode-mac-touchbar/commit/25cd1288bee4129cc6009e67d38bfae8c2fade4e
