### ISSUE TITLE
Custom buttons disappear while typing

### ISSUE THREAD

**Issue by bpawel10** [on2-dev/nasc-vscode-mac-touchbar#46]
Just a few days ago my touch bar always looked like this in VS Code:
<img width="1004" alt="Zrzut paska Touch Bar 2020-09-22 o 10 45 24" src="https://user-images.githubusercontent.com/10183865/93861805-65800d80-fcc1-11ea-80f3-00511b6f5943.png">

But now as soon as text editor or any text field is active, my own buttons are replaced with the keyboard:
<img width="1004" alt="Zrzut paska Touch Bar 2020-09-22 o 10 45 32" src="https://user-images.githubusercontent.com/10183865/93861970-a9731280-fcc1-11ea-8999-3868f2e394c1.png">

**Comment by hacknug** [comment]
Same here. Any insight on this would be greatly appreciated 🙏

**Comment by bpawel10** [comment]
It works again, I guess VS Code update fixed it.
